name: TESSERACT-TRAINING

on:
  workflow_dispatch

jobs:
  training:
    name: Training/Finetuning Tesseract for OCR Recognition
    runs-on: ubuntu-latest
    env:
      TESSDATA_PREFIX: /usr/share/tesseract-ocr/5/tessdata/best
      MODEL_NAME: test_deu_model
      DATA_DIR_TRAINING: $PWD/data
      MAX_ITERATIONS: 100000
      EPOCHS: 100
      IMG_EXT: tif
      MODEL_LANG: deu
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Dependencies Tesseract incl. Training Tools
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            automake \
            ca-certificates \
            libleptonica-dev \
            libtool \
            autoconf \
            g++ \
            make \
            pkg-config \
            cmake \
            git \
            curl \
            libjpeg \
            openjpeg \
            libjpeg8-dev \
            libopenjp2-7-dev \
            giflib \
            libgif-dev \
            libpng \
            libpng-dev \
            libtiff \
            libtiff5-dev \
            webp \
            libwebpdemux2 \
            libwebp-dev \
            zlib \
            zlib1g-dev \
            archive \
            libarchive-dev \
            libcurl4-openssl-dev \
            libicu-dev \
            libpango1.0-dev \
            libcairo2-dev \
            apt-transport-https
      - name: Install Leptonica
        run: |
          git clone git@github.com:microsoft/vcpkg.git
          cd vcpkg
          ./bootstrap-vcpkg.sh # "./bootstrap-vcpkg.bat" for powershell
          ./vcpkg integrate install
          ./vcpkg install leptonica
      - name: Install Tesseract
        run: |
          git clone git@github.com:tesseract-ocr/tesseract.git
          cd tesseract
          ./autogen.sh
          ./configure --disable-graphics
          make
          sudo make install
          sudo ldconfig
          make training
          sudo make training-install
      - name: Install traineddata files
        run: |
          wget https://notesalexp.org/tesseract-ocr5/jammy/pool/main/t/tesseract-lang-best/tesseract-ocr-deu-best_5.0.0+git37-e2aad9b-2_all.deb
          sudo dpkg -i tesseract-ocr-deu-best_5.0.0+git37-e2aad9b-2_all.deb
          wget https://notesalexp.org/tesseract-ocr5/jammy/pool/main/t/tesseract-lang-best/tesseract-ocr-eng-best_5.0.0+git37-e2aad9b-2_all.deb
          sudo dpkg -i tesseract-ocr-eng-best_5.0.0+git37-e2aad9b-2_all.deb
      - name: create ground-truth
        run: |
          mkdir -p $DATA_DIR_TRAINING/$MODEL_NAME-ground-truth
          git clone git@github.com:linxOD/hocr-img-line-extraction.git
          cd hocr-img-line-extraction
          ./scripts/install_dep.sh
          # download sample images and uncomment next line !!!!
          # e.g. wget https://url-to-images
          ./hocr-start.sh
          # copy images to training folder
          mv ./my_img/ground-truth/* $DATA_DIR_TRAINING/$MODEL_NAME-ground-truth/
      - name: Install Tesseract Language Data and train model
        run: |
          git clone git@github.com:tesseract-ocr/tesstrain.git
          cd tesstrain
          make tesseract-langdata DATA_DIR=$DATA_DIR_TRAINING
          make training MODEL_NAME=$MODEL_NAME EPOCHS=$EPOCHS MAX_ITERATIONS=$MAX_ITERATIONS